//! Compile the gRPC proto with serde-capable messages (pbjson). Prefer a system
//! `protoc` (nix nativeBuildInput = protobuf); fall back to the vendored binary
//! for local dev builds.
//!
//! `proto/breathe.proto` is GENERATED by grpc-forge from `spec/breathe.openapi.yaml`
//! (the source of truth) — `grpc-forge proto --spec ... --package breathe.v1`.
//! Do not hand-edit it; regenerate when the spec changes.
use std::path::PathBuf;

fn main() {
    if std::env::var_os("PROTOC").is_none() && which::which("protoc").is_err() {
        if let Ok(p) = protoc_bin_vendored::protoc_bin_path() {
            // SAFETY: build scripts are single-threaded; setting PROTOC for tonic-build.
            unsafe {
                std::env::set_var("PROTOC", p);
            }
        }
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let descriptor_path = out_dir.join("proto_descriptor.bin");

    // `compile_well_known_types()` removes prost's default `.google.protobuf →
    // ::prost_types` extern so the pbjson-types extern is the only one
    // (otherwise: "duplicate extern Protobuf path .google.protobuf").
    let mut config = prost_build::Config::new();
    config.compile_well_known_types();
    config.extern_path(".google.protobuf", "::pbjson_types");
    config.file_descriptor_set_path(&descriptor_path);

    tonic_build::configure()
        .compile_protos_with_config(config, &["proto/breathe.proto"], &["proto"])
        .expect("compile proto/breathe.proto");

    let descriptor_set = std::fs::read(&descriptor_path).expect("read descriptor set");
    pbjson_build::Builder::new()
        .register_descriptors(&descriptor_set)
        .expect("register descriptors")
        .build(&[".breathe.v1"])
        .expect("build pbjson serde impls");

    println!("cargo:rerun-if-changed=proto/breathe.proto");
}
